version: '3.1'

services:
  pgdb:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - ./pgdata:/data/postgres
    depends_on:
      - pgadmin
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ticolucas7@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2022!"
    ports:
      - "16543:80"
    networks:
      - postgres-network

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8080:8080
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
