export const mockPokemonEntity = () => ({
  name: 'any_pokemon_name',
  heigth: 1,
  weight: 1,
  sprite_front_default: 'any_sprite_front_default',
  sprite_front_female: 'any_sprite_front_female',
  sprite_front_shiny: 'any_sprite_front_shiny',
  sprite_front_shiny_female: 'any_sprite_front_shiny_female',
  sprite_back_default: 'any_sprite_back_default',
  sprite_back_female: 'any_sprite_back_female',
  sprite_back_shiny: 'any_sprite_back_shiny',
  sprite_back_shiny_female: 'any_sprite_back_shiny_female',
  hp: 1,
  attack: 1,
  defense: 1,
  special_attack: 1,
  special_defense: 1,
  speed: 1,
  location_area: 'any_location_area',
});
